### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by benreynwar** [maltanar/axi-in-chisel#1]
You have no license in the repository.  I was wondering whether I could use this or not.

**Comment by maltanar** [comment]
Feel free to use this if it's useful, I've now added the MIT license into the repo.

[fpga-tidbits](https://github.com/maltanar/fpga-tidbits/) has more AXI in Chisel stuff that might come in handy, though the idea there is not direct interfacing of AXI but rather defining a simple intermediate memory access layer of sorts, then using adapters to talk to AXI.
